import Head from "next/head";
import Image from "next/image";
import { Inter, Montserrat } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Layout } from "@/components/layout";

const montserrat = Montserrat({ subsets: ["latin"] });

export default function Home() {
  return (<Layout title="NextBasket" keywords="" description="" >
    <>
      {/* <Head>
        <title>NextBasket E-commerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <main className={''}>
        <div className={''}>
          <h1 className="">Hello World</h1>
        </div>
      </main>
    </>
  </Layout>
  );
}

