import PhoneIcon from './phone.svg'
import MailIcon from './mail.svg'
import InstagramIcon from './instagram.svg'
import FacebookIcon from './facebook.svg'
import TwitterIcon from './twitter.svg'
import YoutubeIcon from './youtube.svg'
import ArrowDownIcon from './arrow-down.svg'
import UserIcon from './user.svg'
import MagnifierIcon from './magnifier.svg'
import CartIcon from './cart.svg'
import HeartIcon from './heart.svg'
import BookReaderIcon from './book-reader.svg'
import CarbonBookIcon from './carbon_book.svg'
import IndicatorIcon from './indicator.svg'
import AlarmIcon from './alarm.svg'
import AlbumIcon from './album.svg'
import ArrowRightIcon from './arrow-right.svg'
import ArrowRightv2Icon from './arrow-right-v2.svg'
import ArrowRightv3Icon from './arrow-right-v3.svg'
import ArrowLeftv3Icon from './arrow-left-v3.svg'
import TagIcon from './tag.svg'
import StarFilledIcon from './star-filled.svg'
import StarEmptyIcon from './star-empty.svg'
import Facebookv2Icon from './facebook-v2.svg'
import Twitterv2Icon from './twitter-v2.svg'
import Instagramv2Icon from './instagram-v2.svg'
import GreenLineIcon from './green-line.svg'
import AwsIcon from './aws.svg'
import BingoIcon from './bingo-logo.svg'
import BirdIcon from './bird-logo.svg'
import LyftIcon from './lyft.svg'
import StripeIcon from './stripe.svg'
import HooliIcon from './hooli.svg'
import CircleBlueIcon from './circle-blue.svg'
import CircleGreenIcon from './circle-green.svg'
import CircleOrangeIcon from './circle-orange.svg'
import CircleBlackIcon from './circle-black.svg'
import BasketIcon from './basket.svg'
import LikeIcon from './like.svg'
import MoreIcon from './more.svg'
import MenuIcon from './menu-bar.svg'

export {
    PhoneIcon, MailIcon, InstagramIcon, FacebookIcon, TwitterIcon, YoutubeIcon, ArrowDownIcon, UserIcon, MagnifierIcon, CartIcon, HeartIcon, BookReaderIcon, IndicatorIcon, CarbonBookIcon, AlarmIcon, AlbumIcon, ArrowRightIcon, ArrowRightv2Icon, ArrowRightv3Icon, ArrowLeftv3Icon, TagIcon, StarFilledIcon, StarEmptyIcon, Facebookv2Icon, Twitterv2Icon, Instagramv2Icon, GreenLineIcon, AwsIcon, BingoIcon, BirdIcon, LyftIcon, StripeIcon, HooliIcon, CircleBlueIcon, CircleGreenIcon, CircleOrangeIcon, CircleBlackIcon, BasketIcon, LikeIcon, MoreIcon, MenuIcon
}